### ISSUE TITLE
Link modules titles to view in explorer

### ISSUE THREAD

**Issue by avive** [spacemeshos/dash-frontend#10]
Link titles such as `transactions` to the transactions screen on the public explorer for the same network.
e.g. `https://explore.testnet-124.spacemesh.io/txs`
Note: I'm going to list feature ideas I get from the team here for future dev iterations on this project.

**Comment by Motzart** [comment]
Could you provide more info about link for each block 
transactions it's clear:
Active Smeshers - smeshers page
Accounts - accounts page
Smeshing Rewards - rewards page
Circulation - ?
Security - ? 
Also how it's look likes, we have to highlight the link - underline, hover effect ?

**Comment by avive** [comment]
- No display changes - just underline on hover.
- The actual URLs need to be obtained from the deployment configuration (see spec for deploying dash and explore for network shared).
- Security should link to the Activations page.
- No link for circulation for now.

**Comment by Motzart** [comment]
just for clarify - Security should link to the Activations page - we don't have page for all activations, we have only for each smesher

**Comment by avive** [comment]
You are right. Ignore for now.

**Comment by Motzart** [comment]
Done

**Comment by avive** [comment]
Verified.
