### ISSUE TITLE
Bar graphs hover tooltip content

### ISSUE THREAD

**Issue by avive** [spacemeshos/dash-frontend#14]
[data_item]
[time_ego]
[Epoch number]

e.g:

1,230.21 SMH
3d:2h ago
Epoch 21

**Comment by Motzart** [comment]
I need more info that about each tooltip content, to make things right
active smesher -  
transaction -
accounts - 
smeshing rewards - 
security - 
circulation -

**Comment by avive** [comment]
- Age should be the epoch start time

# Active Smeshers
- 50 Smeshers
- 2 days ago
- Epoch 5

# Accounts
- 51 Accounts
- 3 days ago
- Epoch 6

# Smeshing Rewards
- 3,250.312 SMH
- 4 days ago
- Epoch 8

# Security
- 50 TB
- 3 days ago
- Epoch 3

# Circulation
- 1,234.56 SMH
- 20 days ago
- Epoch 3

# Transactions
- 5,231 Transactions
- 17 days ago
- Epoch 2

**Comment by Motzart** [comment]
done

**Comment by avive** [comment]
I see 2 issues on the current deployment:
1. The text is not like what's described above. e.g. there is no 'age' label or a label:value format - see the comment above for the requested format.
2. The 2nd line item (age) should be the epoch start time of the epoch of the data. It is showing few seconds ago for all epochs for me...

**Comment by avive** [comment]
confirmed.
