### ISSUE TITLE
Network status indicator goes read

### ISSUE THREAD

**Issue by avive** [spacemeshos/dash-frontend#23]
1. Open the tn 122 explorer in your browser and leave it open for a while. https://stage-dash.spacemesh.io/
2. After some time, the network status indicator changes from green to red.
3. Refresh the page - it goes green again.
Expected: network status to stay green while the network is alive and there's no error from the backend

**Comment by despablos** [comment]
fixed

**Comment by avive** [comment]
It is actually a good time to see this issue for tn 122 which has a stuck verified layer but the color in the explore is orange - it should be red so please have a look and fix...

**Comment by Motzart** [comment]
actually yes, my mistake, forgot to update stage, currently - done
