### ISSUE TITLE
Minor Global Updates

### ISSUE THREAD

**Issue by avive** [spacemeshos/dash-frontend#24]
1. Replace 2 top links with:
- `Join Testnet`. url: https://spacemesh.io/testnet/
- `Explore Testnet`. url: https://stage-explore.spacemesh.io/

2. Remove 'Devnet' from the right-side drop-down so only Tweedledee is available.
3. Testnet title in drop-down should be the friendly name (same as in discovery file): `TweedleDee Open Testnet 122`
4. Clicking on logo should browse `https://spacemesh.io`

Automation notes: once dash is deployed via automation and uses url from discovery service, use information from the discovery service: explorer url and network name so we don't need to manually update these for new deployments.

**Comment by despablos** [comment]
fixed

**Comment by avive** [comment]
Confirmed.
