### ISSUE TITLE
Don't use hard-coded network info

### ISSUE THREAD

**Issue by avive** [spacemeshos/dash-frontend#31]
The dashboard needs to be updated based on the info in https://discover.spacemesh.io/networks.json .
It is okay to assume for now that there is only 1 network specified via this url.
- The dash drop-down should display that network # and friendly name.
- The link to explorer should be updated to link to the correct explorer for the current network.
- The data in the dash should be for that network.

For example, right now on dash, TN 122 is displayed as an option and the link to the explorer is incorrect. Expected dash to only show devnet20 in the drop down, display its friendly name and data and explorer link to take user to devnet 20 explorer.

**Comment by Motzart** [comment]
fixed
