### ISSUE TITLE
Sliding Scale Overlapping Styles

### ISSUE THREAD

**Issue by vomcent** [spacemeshos/dash-frontend#38]
For Capacity and ratios (bottom 2 statistics), the horizontal line on the sliding scale is missing missing, and the line indicating position on the scale is white even in light mode.
Current:
<img width="504" alt="Screen Shot 2021-01-29 at 1 27 17 PM" src="https://user-images.githubusercontent.com/49878947/106313174-c8684f00-6235-11eb-8c00-51e8d4d3138c.png">
Expected:
<img width="549" alt="Screen Shot 2021-01-29 at 1 27 07 PM" src="https://user-images.githubusercontent.com/49878947/106313176-c8684f00-6235-11eb-8bf3-a2836b119888.png">

Additionally, when dealing with numbers that overlap with the markings on the scale, I redesigned a few different styles in order to make sure the chart is always clear to read. Can also be seen [here on figma.](https://www.figma.com/file/6bbFkIAzVu36bIpUNnMqoy/Smapp-Designs?node-id=7373%3A126)

<img width="987" alt="Screen Shot 2021-01-29 at 1 28 23 PM" src="https://user-images.githubusercontent.com/49878947/106313323-01082880-6236-11eb-9036-d783d46fd0ef.png">

**Comment by Motzart** [comment]
done
