### ISSUE TITLE
Replace empty map with image

### ISSUE THREAD

**Issue by avive** [spacemeshos/dash-frontend#54]
It doesn't look like the geo heat map feature is going to be working for sm 0.2 so please replace this module temporary per this mock. 

![dash](https://user-images.githubusercontent.com/96002/126456826-a9bb8885-c7b6-4070-b779-0c0a8e302995.png)

Figma: 

https://www.figma.com/file/6bbFkIAzVu36bIpUNnMqoy/Smapp-Designs?node-id=5413%3A817

**Comment by Primaveralina** [comment]
The 3 params in the bottom left corner, are they dynamic or static? If dynamic - where the data's coming from?

**Comment by avive** [comment]
The data comes from the network's node config file. However, I would remove this whole label for release 0.2 and we'll add it back when we finish with the heat map feature.

**Comment by Primaveralina** [comment]
@avive pls provide the pic for the light mode as well. we have only found dark mode pic.

**Comment by vomcent** [comment]
![Mesh the world light](https://user-images.githubusercontent.com/49878947/127175103-53ff1247-cb75-43c3-8e2e-d7c5c6ab2106.png)
![Mesh the world](https://user-images.githubusercontent.com/49878947/127175106-f0acf11d-27c6-4ab2-8a00-9dac4686d42d.png)

Here are two versions, let me know how these work. 

I can also supply versions with no background color and just the globe and mesh, if that's easier to implement.

**Comment by avive** [comment]
Please add all assets to Figma :-)

**Comment by vomcent** [comment]
Sorry about that, find the dashboard image assets [here.](https://www.figma.com/file/6bbFkIAzVu36bIpUNnMqoy/Smapp-Designs?node-id=8594%3A39219). I included full sized uncropped assets as well as the cropped versions as they appear in the dashboard design.

**Comment by avive** [comment]
Thanks @vomcent. @Primaveralina - provided as asked.

**Comment by Primaveralina** [comment]
Thanks @avive. Will add

**Comment by Motzart** [comment]
done

**Comment by avive** [comment]
Confirmed. good job!
