### ISSUE TITLE
Undefined label in dash circulation info-graphics

### ISSUE THREAD

**Issue by Primaveralina** [spacemeshos/dash-frontend#62]
the devnet-kirill-2 dashboard:

In the circulation info-graphics the amount displayed text is ‘9,800.undefined SMH’
![144394773-f2564c08-2680-4e75-b5fa-b3846c6e4cb0](https://user-images.githubusercontent.com/33487597/144825768-5c3b7325-440c-4b32-a920-4477723cd47d.jpeg)

**Comment by Motzart** [comment]
done

**Comment by Primaveralina** [comment]
In production
